### ISSUE TITLE
how to set up uppy server in rails app?

### ISSUE THREAD

**Issue by floodico** [transloadit/uppy-server#46]
Hello!
How we can set up uppy server in our rails app? We are already integrate uppy uploader into our app, but if we want to use other storages like google drive, dropbox and other, we need to set up uppy server, well?
We try to do this using browserify-rails gem, but we can't require 'express'.
Do we must use express to set up uppy server?
Thank for your ideas!

**Comment by kvz** [comment]
Hi, Uppy-server bundles express so you have a ready to go server after you `npm install -g uppy-server`. If you don't care for running that yourself, you could also check out our service which offers hosted uppy-servers at https://transloadit.com

**Comment by ifedapoolarewaju** [comment]
Hello @floodico, browseriy-rails seems not to be a good fit for this problem, because it is used for bundling client side javascript libraries (or so it seems). Uppy-server however, works in the nodejs environment (i.e server-side library).

but you don't necessarily have to write any nodejs code to use uppy-server, with the help of the [standalone server](https://github.com/transloadit/uppy-server#run-as-standalone-server), you can simply install it with:

`npm install -g uppy-server`

and get it started with the command:

`$ uppy-server`

This would start the server on `localhost:3020` (but can be customized of course), and then all you'd need to do is link your intended rails endpoint to the running uppy-server url (i.e `localhost:3020`)

However, if this seems as too much trouble, you can look to https://transloadit.com as @kvz suggested :)

**Comment by floodico** [comment]
@ifedapoolarewaju thank you
