### ISSUE TITLE
documentation mistaken?

### ISSUE THREAD

**Issue by sandro-pasquali** [transloadit/uppy-server#50]
Hi,

I am unable to register google drive as a provider when using this as an Express middleware.

Re: https://github.com/transloadit/uppy-server/blob/master/src/server/provider/index.js#L68:

```
const middleware = (req, res, next, providerName) => {
    if (providers[providerName] && validOptions(req.uppy.options)) { <- this check always fails
```
I'm getting `main` for `providerName` here (not sure why), and `providers` are listed as follows:

```
{ dropbox: [Function: DropBox],
  drive: [Function: Drive],
  instagram: [Function: Instagram] }
```
I'm attaching to an Express server, so following the docs I'm doing this:

```
var app = express()
app.use(bodyParser.json())
...
// be sure to place this anywhere after app.use(bodyParser.json())
const options = {
  providerOptions: {
    google: {
      key: 'my key',
      secret: 'my secret'
    }
  },
  server: {
    ...
  },
  filePath: '...'
}

app.use(uppy.app(options))
```
Note that the docs show `google` as a provider, when it seems `drive` is the correct key.

And of course where is `main` coming from?

Thanks!

**Comment by ifedapoolarewaju** [comment]
@sandro-pasquali thank you for reporting.

The documentation is not mistaken, the correct option to set the google credentials is:

```
google: {
      key: 'my key',
      secret: 'my secret'
    }
```
it is only referred to as drive internally. The reason is because, while the google `key` and `secret` may be used for google photos, and google drive. The api we currently support internally is google drive. But we can also in the later future use this same google credentials for google photos api as well.

Per the error you are facing, I'm not able to reproduce from my end. What version of uppy server are you using? And can you share a more detailed version of the code you are using.

Also if it helps, I have created an example project [here](https://github.com/transloadit/uppy/tree/master/examples/uppy-with-server) that attaches uppy to an express server just the way you are trying to use it. It is a lean, working example, and it might maybe help you spot what you could be doing differently
